# Generated by Django 4.0.6 on 2022-08-11 14:10

import datetime
from django.db import migrations, models
import django.db.models.deletion
from django.utils.timezone import utc


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArchiveBNDESOperacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client', models.IntegerField()),
                ('logs', models.JSONField()),
                ('delete_data', models.DateField(default=datetime.datetime(2022, 8, 11, 11, 10, 25, 924515))),
            ],
            options={
                'verbose_name': 'BNDES.Archive',
                'db_table': 'tb_archive_bndes_operacao',
                'ordering': ('delete_data',),
            },
        ),
        migrations.CreateModel(
            name='Empresa',
            fields=[
                ('cnpj_id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('data_search', models.DateTimeField(default=datetime.datetime(2022, 8, 11, 14, 10, 25, 923311, tzinfo=utc))),
                ('validity_day', models.DateTimeField(default=datetime.datetime(2022, 9, 10, 14, 10, 25, 923349, tzinfo=utc))),
            ],
            options={
                'verbose_name': 'BNDES.Empresa',
                'db_table': 'tb_empresa_cnpj',
            },
        ),
        migrations.CreateModel(
            name='Operacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('agente_financeiro', models.CharField(default='null', max_length=100)),
                ('operacaoDireta', models.CharField(default='null', max_length=10)),
                ('inovacao', models.CharField(default='null', max_length=10)),
                ('subsetorApoiado', models.CharField(default='null', max_length=100)),
                ('reembolsavel', models.CharField(default='null', max_length=10)),
                ('uf', models.CharField(default='null', max_length=100)),
                ('produtoBndes', models.CharField(default='null', max_length=100)),
                ('dataContratacao', models.CharField(default='null', max_length=100)),
                ('liquidada', models.CharField(default='null', max_length=10)),
                ('setorApoiado', models.CharField(default='null', max_length=100)),
                ('custoFinanceiro', models.CharField(default='null', max_length=100)),
                ('cnae', models.CharField(default='null', max_length=100)),
                ('formaApoio', models.CharField(default='null', max_length=100)),
                ('ano', models.IntegerField(default=0)),
                ('valorDesembolsado', models.FloatField(default=0.0, null=True)),
                ('porteCliente', models.CharField(default='null', max_length=100, null=True)),
                ('municipio', models.CharField(default='null', max_length=100, null=True)),
                ('prazoAmortizacao', models.IntegerField(default=0)),
                ('cnpjAberto', models.CharField(default='null', max_length=100, null=True)),
                ('instrumentoBndes', models.CharField(default='null', max_length=100, null=True)),
                ('naturezaCliente', models.CharField(default='null', max_length=100, null=True)),
                ('prazoCarencia', models.CharField(default='null', max_length=100, null=True)),
                ('tipoOperacao', models.CharField(default='null', max_length=100, null=True)),
                ('cliente', models.CharField(default='null', max_length=100, null=True)),
                ('tipoDocumento', models.CharField(default='null', max_length=100, null=True)),
                ('fonteRecursos', models.CharField(default='null', max_length=100, null=True)),
                ('cnpjAgenteFinanceiro', models.CharField(default='null', max_length=100, null=True)),
                ('taxaJuros', models.SmallIntegerField(default=0)),
                ('areaOperacional', models.CharField(default='null', max_length=200, null=True)),
                ('codigoMunicipio', models.CharField(default='null', max_length=100, null=True)),
                ('ramoAtividade', models.CharField(blank=True, default='null', max_length=200, null=True)),
                ('cnpj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BNDESIntegration.empresa')),
            ],
            options={
                'verbose_name': 'operacoe',
                'db_table': 'tb_bndes_operacao',
            },
        ),
        migrations.CreateModel(
            name='BNDESOperacoes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logs', models.JSONField()),
                ('data_created', models.DateTimeField(auto_now_add=True)),
                ('client', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='BNDESIntegration.empresa')),
            ],
            options={
                'verbose_name': 'BNDES.json.operacoe',
                'db_table': 'tb_bndes_operacao_json',
                'ordering': ('data_created',),
            },
        ),
    ]
