# Generated by Django 4.0.6 on 2022-08-11 14:10

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BNDESIntegration', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivebndesoperacoes',
            name='delete_data',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 11, 10, 28, 272022)),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='data_search',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 14, 10, 28, 270682, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='empresa',
            name='validity_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 14, 10, 28, 270725, tzinfo=utc)),
        ),
    ]
