# Generated by Django 4.0.6 on 2022-08-11 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BNDESIntegration', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='transaction',
            options={'verbose_name': 'transaction'},
        ),
        migrations.AlterField(
            model_name='archivebndestransaction',
            name='delete_data',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 16, 23, 29, 642706)),
        ),
        migrations.AlterField(
            model_name='company',
            name='data_search',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 19, 23, 29, 641098, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='validity_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 19, 23, 29, 641150, tzinfo=utc)),
        ),
        migrations.AlterModelTable(
            name='transaction',
            table='tb_bndes_transaction',
        ),
    ]
