# Generated by Django 4.0.6 on 2022-08-11 19:23

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('BNDESIntegration', '0003_alter_archivebndestransaction_delete_data_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='archivebndestransaction',
            name='delete_data',
            field=models.DateField(default=datetime.datetime(2022, 8, 11, 16, 23, 32, 386012)),
        ),
        migrations.AlterField(
            model_name='company',
            name='data_search',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 11, 19, 23, 32, 384097, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='company',
            name='validity_day',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 10, 19, 23, 32, 384156, tzinfo=utc)),
        ),
    ]
