# Generated by Django 4.0.6 on 2022-08-04 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacoes',
            name='cnpj',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
