# Generated by Django 4.0.6 on 2022-08-04 19:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0002_operacoes_cnpj'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='empresa',
            name='id',
        ),
        migrations.AlterField(
            model_name='empresa',
            name='cnpj',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='cnpj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='polls.empresa'),
        ),
    ]
