# Generated by Django 4.0.6 on 2022-08-04 19:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0003_remove_empresa_id_alter_empresa_cnpj_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='empresa',
            old_name='cnpj',
            new_name='cnpj_id',
        ),
    ]
