# Generated by Django 4.0.6 on 2022-08-05 01:29

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0004_rename_cnpj_empresa_cnpj_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='operacoes',
            name='delete_time',
            field=models.DateTimeField(default=django.utils.timezone.now, null=True),
        ),
        migrations.AddField(
            model_name='operacoes',
            name='update_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
