# Generated by Django 4.0.6 on 2022-08-05 01:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0005_operacoes_delete_time_operacoes_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacoes',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
