# Generated by Django 4.0.6 on 2022-08-05 01:34

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0006_alter_operacoes_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacoes',
            name='delete_time',
            field=models.DateTimeField(default=datetime.timedelta(days=30), null=True),
        ),
    ]
