# Generated by Django 4.0.6 on 2022-08-05 01:37

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0007_alter_operacoes_delete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacoes',
            name='delete_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 9, 4, 1, 37, 10, 386412, tzinfo=utc), null=True),
        ),
    ]
