# Generated by Django 4.0.6 on 2022-08-05 01:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0008_alter_operacoes_delete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacoes',
            name='delete_time',
            field=models.DateTimeField(null=True),
        ),
    ]
