# Generated by Django 4.0.6 on 2022-08-05 13:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0010_alter_operacoes_delete_time'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='operacoes',
            name='delete_time',
        ),
    ]
