# Generated by Django 4.0.6 on 2022-08-05 13:57

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0011_remove_operacoes_delete_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacoes',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 13, 57, 10, 631731, tzinfo=utc)),
        ),
    ]
