# Generated by Django 4.0.6 on 2022-08-05 13:58

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0012_alter_operacoes_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacoes',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 10, 58, 12, 393615)),
        ),
    ]
