# Generated by Django 4.0.6 on 2022-08-05 14:14

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0013_alter_operacoes_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacoes',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 14, 14, 37, 762419, tzinfo=utc)),
        ),
    ]
