# Generated by Django 4.0.6 on 2022-08-05 15:07

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0014_alter_operacoes_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacoes',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 15, 7, 53, 144347, tzinfo=utc)),
        ),
    ]
