# Generated by Django 4.0.6 on 2022-08-05 18:46

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('polls', '0015_alter_operacoes_update_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operacoes',
            name='agente_financeiro',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='ano',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='areaOperacional',
            field=models.CharField(default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='cliente',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='cnae',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='cnpjAberto',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='cnpjAgenteFinanceiro',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='codigoMunicipio',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='custoFinanceiro',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='dataContratacao',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='fonteRecursos',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='formaApoio',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='instrumentoBndes',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='municipio',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='naturezaCliente',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='porteCliente',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='prazoCarencia',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='produtoBndes',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='ramoAtividade',
            field=models.CharField(blank=True, default='null', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='setorApoiado',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='subsetorApoiado',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='tipoDocumento',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='tipoOperacao',
            field=models.CharField(default='null', max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='uf',
            field=models.CharField(default='null', max_length=100),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='update_time',
            field=models.DateTimeField(default=datetime.datetime(2022, 8, 5, 18, 46, 37, 205879, tzinfo=utc)),
        ),
        migrations.AlterField(
            model_name='operacoes',
            name='valorDesembolsado',
            field=models.FloatField(default=0.0, null=True),
        ),
    ]
